name: user_library
description: Library for storing user library and some utility methods
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  database_api:
    path: ../../database_api
  hive: ^2.2.3
  hive_generator: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
