name: custom_dio
description: Has extensions for dio that add interceptors
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dio: ^5.0.1
  flutter_inappwebview: ^5.7.2+3
  app_logging:
    path: ../../app_logging

dev_dependencies:
  alfred: ^1.0.0+1
  lints: ^2.0.0
  test: ^1.21.0
