name: database_api
description: Contains data models for database
version: 0.1.0
publish_to: none
environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  hive: ^2.2.3
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  uuid: ^3.0.7
