name: manga_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  manga_database:
    path: ../../apis/local_storage/manga_database
  manga_sources:
    path: ../../apis/manga/manga_sources

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
