name: manga_database
description: houses the code responsible for the manga database
version: 0.1.0
publish_to: none
environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  app_logging:
    path: ../../../utilities/app_logging
  hive: ^2.2.3
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  uuid: ^3.0.7
  woozy_search: ^2.0.3
