name: manga_database
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  app_logging:
    path: ../../../utilities/app_logging
  collection: 1.17.0
  hive: ^2.2.3
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  uuid: ^3.0.7
  woozy_search: ^2.0.3
