name: manga_sources
description: Contains all manga sources and a helper class
version: 0.1.0
publish_to: none
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  custom_dio:
    path: ../../../utilities/network/custom_dio
  dio: ^5.0.2
  html: ^0.15.2
  manga_source_base:
    path: ../manga_source_base
  collection: 1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
